-- ==========================================
-- MIGRACIÓN 007: MÓDULO FINANCIERO
-- Finanzas y Control Contractual
-- ==========================================

-- Tabla de Contratos
CREATE TABLE IF NOT EXISTS CONTRATOS (
    ID_CONTRATO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CONTRATO VARCHAR(255) NOT NULL,
    CLIENTE VARCHAR(255) NOT NULL,
    CANTIDAD_POZOS INT NOT NULL DEFAULT 0,
    VALOR_UNITARIO_BASE_USD DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    MONTO_TOTAL_CONTRACTUAL DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    BACKLOG_RESTANTE DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    PLAZO_PAGO_DIAS INT NOT NULL DEFAULT 30,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ESTADO ENUM('ACTIVO', 'SUSPENDIDO', 'FINALIZADO', 'CANCELADO') DEFAULT 'ACTIVO',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Certificaciones
CREATE TABLE IF NOT EXISTS CERTIFICACIONES (
    ID_CERTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_CONTRATO INT NOT NULL,
    ID_WELL VARCHAR(50) NOT NULL,
    FECHA_CERTIFICACION DATE NOT NULL,
    MONTO_CERTIFICADO DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    PORCENTAJE_AVANCE DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    ESTADO ENUM('PENDIENTE_FACTURA', 'FACTURADO', 'COBRADO') DEFAULT 'PENDIENTE_FACTURA',
    OBSERVACIONES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATOS(ID_CONTRATO) ON DELETE RESTRICT,
    FOREIGN KEY (ID_WELL) REFERENCES WELL(ID_WELL) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Facturas
CREATE TABLE IF NOT EXISTS FACTURAS (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CERTIFICACION INT NOT NULL,
    NUMERO_FACTURA VARCHAR(50) NOT NULL UNIQUE,
    FECHA_FACTURA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MONTO DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    ESTADO ENUM('EMITIDA', 'PENDIENTE', 'COBRADA', 'VENCIDA', 'ANULADA') DEFAULT 'EMITIDA',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CERTIFICACION) REFERENCES CERTIFICACIONES(ID_CERTIFICACION) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Cobranzas
CREATE TABLE IF NOT EXISTS COBRANZAS (
    ID_COBRANZA INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    FECHA_COBRANZA DATE NOT NULL,
    MONTO_COBRADO DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    MEDIO_PAGO ENUM('TRANSFERENCIA', 'CHEQUE', 'EFECTIVO', 'DEPOSITO') NOT NULL,
    REFERENCIA_PAGO VARCHAR(100),
    ESTADO ENUM('PENDIENTE', 'COMPLETADA', 'RECHAZADA') DEFAULT 'PENDIENTE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Costos Reales
CREATE TABLE IF NOT EXISTS COSTOS_REALES (
    ID_COSTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_WELL VARCHAR(50) NOT NULL,
    ETAPA VARCHAR(100) NOT NULL,
    CONCEPTO VARCHAR(255) NOT NULL,
    MONTO_USD DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    FECHA DATE NOT NULL,
    PROVEEDOR VARCHAR(255),
    DOCUMENTO_SOPORTE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_WELL) REFERENCES WELL(ID_WELL) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Flujo de Fondos Proyectado
CREATE TABLE IF NOT EXISTS FLUJO_FONDOS (
    ID_FLUJO INT AUTO_INCREMENT PRIMARY KEY,
    PERIODO VARCHAR(7) NOT NULL,
    INGRESOS_PROYECTADOS DECIMAL(15,2) DEFAULT 0.00,
    EGRESOS_PROYECTADOS DECIMAL(15,2) DEFAULT 0.00,
    SALDO_MENSUAL DECIMAL(15,2) DEFAULT 0.00,
    SALDO_ACUMULADO DECIMAL(15,2) DEFAULT 0.00,
    TIPO_PROYECCION ENUM('MENSUAL', 'TRIMESTRAL', 'ANUAL') DEFAULT 'MENSUAL',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PERIODO_TIPO (PERIODO, TIPO_PROYECCION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de Parámetros Macro
CREATE TABLE IF NOT EXISTS PARAMETROS_MACRO (
    ID_PARAMETRO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PARAMETRO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(15,4) NOT NULL,
    UNIDAD VARCHAR(50),
    FECHA_VIGENCIA DATE NOT NULL,
    DESCRIPCION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_certificaciones_contrato ON CERTIFICACIONES(ID_CONTRATO);
CREATE INDEX IF NOT EXISTS idx_certificaciones_well ON CERTIFICACIONES(ID_WELL);
CREATE INDEX IF NOT EXISTS idx_facturas_certificacion ON FACTURAS(ID_CERTIFICACION);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON FACTURAS(ESTADO);
CREATE INDEX IF NOT EXISTS idx_cobranzas_factura ON COBRANZAS(ID_FACTURA);
CREATE INDEX IF NOT EXISTS idx_costos_well ON COSTOS_REALES(ID_WELL);
CREATE INDEX IF NOT EXISTS idx_costos_fecha ON COSTOS_REALES(FECHA);
CREATE INDEX IF NOT EXISTS idx_flujo_periodo ON FLUJO_FONDOS(PERIODO);

-- ==========================================
-- DATOS INICIALES (PARA DESARROLLO)
-- ==========================================

-- Insertar parámetros macro iniciales
INSERT INTO PARAMETROS_MACRO (NOMBRE_PARAMETRO, VALOR, UNIDAD, FECHA_VIGENCIA, DESCRIPCION) VALUES
('COTIZACION_DOLAR', 1050.00, 'ARS/USD', '2025-01-01', 'Cotización referencial del dólar'),
('INFLACION_ANUAL_ESTIMADA', 25.50, '%', '2025-01-01', 'Inflación anual estimada'),
('TASA_INTERES_ANUAL', 45.00, '%', '2025-01-01', 'Tasa de interés anual para cálculos'),
('COSTO_OPORTUNIDAD', 12.00, '%', '2025-01-01', 'Costo de oportunidad del capital')
ON DUPLICATE KEY UPDATE VALOR = VALUES(VALOR);

-- ==========================================
-- TABLA DE AUDITORÍA FINANCIERA
-- ==========================================

CREATE TABLE IF NOT EXISTS AUDITORIA_FINANCIERA (
    ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    TABLA_AFECTADA VARCHAR(50) NOT NULL,
    ID_REGISTRO INT NOT NULL,
    TIPO_OPERACION ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    DATOS_ANTERIORES JSON,
    DATOS_NUEVOS JSON,
    USUARIO VARCHAR(100) NOT NULL,
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS VARCHAR(45)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
